### ISSUE TITLE
"undefined local variable or method `base' for #<Theme:0x00000002a2c950> (NameError)"

### ISSUE THREAD

**Issue by alexbooker** [chriskempson/base16-builder#311]
**Steps to reproduce:**

1. `git clone https://github.com/chriskempson/base16-builder && cd base16-builder`
3. `./base16`

**What happens:**

I get the following output:

```
...
  - ./templates/preview/html.erb                                                                                                                                                        [0/135]
  - ./templates/preview/colors.html.erb
  - ./templates/powerpaint/rcpx.erb
  - ./templates/idea/light.icls.erb
  - ./templates/idea/dark.icls.erb
  - ./templates/prism/light.css.erb
  - ./templates/prism/dark.css.erb
  - ./templates/mou/dark.txt.erb
  - ./templates/mou/light.txt.erb
  - ./templates/mou/dark+.txt.erb
  - ./templates/mou/light+.txt.erb
  - ./templates/conemu/conemu.xml.erb
  - ./templates/konsole/scheme.erb
  - ./templates/konsole/html.erb
  - ./templates/konsole/colorscheme.erb
  - ./templates/secure-shell/light.prefs.js.erb
  - ./templates/secure-shell/dark.prefs.js.erb
  - ./templates/highlight.js/light.css.erb
  - ./templates/highlight.js/dark.css.erb
  - ./templates/gedit/dark.xml.erb
  - ./templates/gedit/light.xml.erb
  - ./templates/mutt/light.256.muttrc.erb
  - ./templates/mutt/dark.256.muttrc.erb
  - ./templates/putty/reg.erb
  - ./templates/qtcreator/dark.xml.erb
  - ./templates/qtcreator/light.xml.erb
  - ./templates/bbedit/light.bbcolors.erb
  - ./templates/bbedit/dark.bbcolors.erb
  - ./templates/i3status/i3status.erb
  - ./templates/codemirror/-dark.css.erb
  - ./templates/codemirror/-light.css.erb
  - ./templates/iterm2/dark.itermcolors.erb
  - ./templates/iterm2/dark.256.itermcolors.erb
  - ./templates/iterm2/light.256.itermcolors.erb
  - ./templates/iterm2/light.itermcolors.erb
  - ./templates/chrome-devtools/light.css.erb
  - ./templates/chrome-devtools/dark.css.erb
  - ./templates/i3/i3.erb
  - ./templates/dmenu/light.erb
(erb):6:in `parse_template_file': undefined local variable or method `base' for #<Theme:0x00000002a2c950> (NameError)
        from /usr/lib/ruby/1.9.1/erb.rb:838:in `eval'
        from /usr/lib/ruby/1.9.1/erb.rb:838:in `result'
        from ./base16:120:in `parse_template_file'
        from ./base16:107:in `block in create_output_files'
        from ./base16:103:in `each'
        from ./base16:103:in `create_output_files'
        from ./base16:45:in `build_single_scheme'
        from ./base16:37:in `block in build_all_schemes'
        from ./base16:36:in `each'
        from ./base16:36:in `build_all_schemes'
        from ./base16:28:in `build'
        from ./base16:275:in `<main>'
```

*Some* outputs are generated successfully but most are missing from the `output` directories. 

**Other:**

I learned about *base16-builder* through [*this*](https://github.com/gabrielflorit/base16-builder) fork which works fine on my machine (XUbuntu 14.04).

**What I have tried:**

- Running as `sudo`

**Comment by kowalskey** [comment]
Hello!
I took liberty to fork repository and provide fix.
Please check whether it works for you.

Looks like one of templates used deprecated syntax.
@chriskempson  I created PR #312 for this ;)

Problematic template was created in e66454c008f90604340742fd367495e73e92f43d .

**Comment by filipebarros** [comment]
https://github.com/chriskempson/base16-builder/pull/306

**Comment by alexbooker** [comment]
@kowalskey Your patch works.

@filipebarros I did not see your patch until I had already tried @kowalskey's.

Thanks. You are both :star:s

**Comment by auduchinok** [comment]
@filipebarros, @kowalskey Thank you!

**Comment by ddre54** [comment]
@kowalskey :+1:

**Comment by hbaughman** [comment]
@kowalskey  @filipebarros Much appreciated!

**Comment by ybakos** [comment]
Uh, can this be merged?

**Comment by alexbooker** [comment]
@ybakos,

Clearly @chriskempson is inactive at the moment.  Just clone someone's fork.
